---
php_versions:
  - php73
  - php74

php73_version:
  - php73
  - php73-php-pecl-apcu-bc
  - php73-php-cli
  - php73-php-pecl-mysql
  - php73-php-gd
  - php73-php-pear
  - php73-runtime
  - php73-php-common
  - php73-php-pecl-msgpack
  - php73-php-pecl-apcu
  - php73-php-mysqlnd
  - php73-php-pecl-igbinary
  - php73-php-mbstring
  - php73-php-pecl-mcrypt
  - php73-php-pecl-memcache
  - php73-php-json
  - php73-php-fpm
  - php73-php-process
  - php73-php-xml
  - php73-php-pdo
  - php73-php-pecl-memcached
  - php73-php-ftp
  - php73-php-xmlwriter
  - php73-php-phar
  - php73-php-sodium
  - php73-php-zlib
  - php73-php-tokenizer
  - php73-php-dom
  - php73-php-xsl
  - php73-php-msgpack
  - php73-php-pdo_sqlite
  - php73-php-filter
  - php73-php-bz2
  - php73-php-pcntl
  - php73-php-sockets
  - php73-php-posix
  - php73-php-bcmath
  - php73-php-session
  - php73-php-simplexml
  - php73-php-intl
  - php73-php-imagick
  - php73-php-sysvsem
  - php73-php-exif
  - php73-php-shmop
  - php73-php-fileinfo
  - php73-php-iconv
  - php73-php-sqlite3
  - php73-php-soap
  - php73-php-calendar
  - php73-php-sysvmsg
  - php73-php-mbstring
  - php73-php-gettext
  - php73-php-imap
  - php73-php-readline
  - php73-php-sysvshm
  - php73-php-curl
  - php73-php-tidy
  - php73-php-xmlrpc
  - php73-php-wddx
  - php73-php-ctype
  - php73-php-memcached
  - php73-php-openssl
  - php73-php-zip

php74_version:
  - php74
  - php74-php-pecl-apcu-bc
  - php74-php-cli
  - php74-php-pecl-mysql
  - php74-php-gd
  - php74-php-pear
  - php74-runtime
  - php74-php-common
  - php74-php-pecl-msgpack
  - php74-php-pecl-apcu
  - php74-php-mysqlnd
  - php74-php-pecl-igbinary
  - php74-php-mbstring
  - php74-php-pecl-mcrypt
  - php74-php-pecl-memcache
  - php74-php-json
  - php74-php-fpm
  - php74-php-process
  - php74-php-xml
  - php74-php-pdo
  - php74-php-pecl-memcached
  - php74-php-ftp
  - php74-php-xmlwriter
  - php74-php-phar
  - php74-php-sodium
  - php74-php-zlib
  - php74-php-tokenizer
  - php74-php-dom
  - php74-php-xsl
  - php74-php-msgpack
  - php74-php-pdo_sqlite
  - php74-php-filter
  - php74-php-bz2
  - php74-php-pcntl
  - php74-php-sockets
  - php74-php-posix
  - php74-php-bcmath
  - php74-php-session
  - php74-php-simplexml
  - php74-php-intl
  - php74-php-imagick
  - php74-php-sysvsem
  - php74-php-exif
  - php74-php-shmop
  - php74-php-fileinfo
  - php74-php-iconv
  - php74-php-sqlite3
  - php74-php-soap
  - php74-php-calendar
  - php74-php-sysvmsg
  - php74-php-mbstring
  - php74-php-gettext
  - php74-php-imap
  - php74-php-readline
  - php74-php-sysvshm
  - php74-php-curl
  - php74-php-tidy
  - php74-php-xmlrpc
  - php74-php-wddx
  - php74-php-ctype
  - php74-php-memcached
  - php74-php-openssl
  - php74-php-zip

group_owner_lib_php: '{{ "nginx" if cluster_setup_mode == 2 or cluster_setup_mode == 3 else "apache" }}'